#!/usr/bin/env python3
"""Generate CONFIGURATION.md's settings reference from the registry in config.py.

The registry (settings.env() calls in config.py) is the single source of
truth for every operator setting: the admin dashboard renders it, and this
script renders the same thing as Markdown so the docs cannot drift from
the code.  tests/test_settings_docs.py fails when the CONFIGURATION.md block is stale.

    python3 tools/settings_docs.py            # print the block
    python3 tools/settings_docs.py --write    # update CONFIGURATION.md in place
    python3 tools/settings_docs.py --check    # exit 1 if CONFIGURATION.md is stale

Only the everyday tier (advanced=False) goes in the CONFIGURATION.md table; advanced
settings are documented by hand in ADVANCED.md, where each has a section,
and the test only checks that every advanced key has one.
"""
from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import config  # noqa: E402,F401 — populates the registry
import settings  # noqa: E402

DOC = os.path.join(ROOT, "CONFIGURATION.md")
START = "<!-- settings-reference:start (generated by tools/settings_docs.py, do not edit by hand) -->"
END = "<!-- settings-reference:end -->"

# Settings that are not in the registry because Python cannot consume them,
# listed here so the reference still mentions them under the right group.
EXTRA_ROWS: dict[str, list[tuple[str, str, str]]] = {
    "Access & serving": [
        ("ADMIN_KEY", "-", "Enables the [admin dashboard](README.md#admin-dashboard) at `/admin`. At least 12 characters. Env-only: it is the one setting the dashboard cannot manage, because it is what protects the dashboard."),
    ],
}


def _cell(text: str) -> str:
    return text.replace("|", "\\|").strip()


def _default(s: settings.Setting) -> str:
    if s.kind == "secret" or s.default == "":
        return "-"
    return f"`{s.default}`"


def render() -> str:
    out: list[str] = [START, ""]
    out.append("Grouped as the admin dashboard groups them. Defaults apply when neither the dashboard nor the environment sets a value. Advanced settings (tuning knobs a running instance needs none of) are in [ADVANCED.md](ADVANCED.md) and behind each group's *Advanced* fold in the dashboard.")
    out.append("")
    for group in settings.ordered_groups():
        rows = [s for s in settings.REGISTRY.values() if s.group == group and not s.advanced]
        extra = EXTRA_ROWS.get(group, [])
        if not rows and not extra:
            continue
        out.append(f"#### {group}")
        out.append("")
        out.append("| Variable | Default | Description |")
        out.append("|---|---|---|")
        for key, default, desc in extra:
            out.append(f"| `{key}` | {default} | {_cell(desc)} |")
        for s in rows:
            desc = s.help
            if s.show_if:
                dep_key, values = s.show_if
                if values == ("*",):
                    desc += f" Only used when `{dep_key}` is set."
                else:
                    desc += " Only used when `" + dep_key + "` is " + " or ".join(f"`{v}`" for v in values) + "."
            if s.kind == "choice":
                desc += " One of " + ", ".join(f"`{c}`" for c in s.choices) + "."
            elif s.kind == "bool":
                desc += " `true` or `false`."
            elif s.kind == "list":
                desc += " Comma-separated."
            out.append(f"| `{s.key}` | {_default(s)} | {_cell(desc)} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def current_block(text: str) -> tuple[int, int] | None:
    a = text.find(START)
    b = text.find(END)
    if a < 0 or b < 0 or b < a:
        return None
    return a, b + len(END)


def main(argv: list[str]) -> int:
    block = render()
    if "--write" in argv or "--check" in argv:
        with open(DOC, encoding="utf-8") as fh:
            text = fh.read()
        span = current_block(text)
        if span is None:
            print(f"CONFIGURATION.md has no {START!r} … {END!r} markers", file=sys.stderr)
            return 2
        updated = text[: span[0]] + block + text[span[1]:]
        if "--check" in argv:
            if updated != text:
                print("CONFIGURATION.md settings reference is stale — run: python3 tools/settings_docs.py --write", file=sys.stderr)
                return 1
            print("CONFIGURATION.md settings reference is up to date")
            return 0
        with open(DOC, "w", encoding="utf-8") as fh:
            fh.write(updated)
        print("CONFIGURATION.md updated")
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
